sonar.projectKey=student-grade-service
sonar.projectName=student-grade-service
sonar.sourceEncoding=UTF-8

sonar.sources=src,include
sonar.tests=tests

sonar.cfamily.compile-commands=build/compile_commands.json

sonar.exclusions=build/**
sonar.test.inclusions=tests/**/*.cpp
